# FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel
FROM nvidia/cuda:12.3.1-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

# RUN rm /etc/apt/sources.list.d/cuda.list
# RUN rm /etc/apt/sources.list.d/nvidia-ml.list

RUN apt-get update && apt-get install -y \
    python3 \
    git \
    vim \
    ffmpeg \
    libsm6 \ 
    libxext6 \
    python3-pip

RUN mkdir -p autobrains 
COPY . autobrains/

WORKDIR autobrains

RUN pip3 install .
RUN mkdir -p logger data